### ISSUE TITLE
有考虑使用跨平台架构构建项目吗

### ISSUE THREAD

**Issue by Supheria** [ModerCore/Moder#30]
如果能在其他平台例如安卓或者Linux上运行此项目就再好不过了。有意向的话我可以试着用Avalonia重构

**Comment by textGamex** [comment]
项目立项之处想着为了高颜值+玩钢丝的应该大部分都是 Windows 操作系统,所以选的 WinUI3, 跨平台感觉并不那么重要.

但现在实际开发了一段时间后, 有些动摇了, 原因有2:
1. 微软对 WinUI 的支持力度令社区失望, 很多问题拖了很久都没解决, 连内存泄漏这种非常影响用户体验的问题都拖了四年
2. WinUI 是不完全开源的, 这就意味着 WinUI 无法从社区获取贡献, 我记得 WinUI 团队就5个人, bug 修复赶不上 issue 提的速度, 所以社区对 WinUI 的前景并不看好. 这里有两个个很有意思的 issue 和讨论 [Great News: All Bugs Will be Fixed In the Year 2041](https://github.com/microsoft/microsoft-ui-xaml/issues/9410), [Ohh...WinUI3 is really dead! - When can we expect the announcement?](https://github.com/microsoft/microsoft-ui-xaml/discussions/9417) 可以看到社区对 WinUI 的看法

但就跨平台而言, 我想有以下几个问题
1. 迁移成本和学习成本
我并不会 Avalonia, 听说跟 WPF 有些相像, 不知道要学多久能上手呢? 而且项目开发这么久, 总感觉有些积重难返.
2. 维护成本
我手头上并没有 Linux 和 MacOS 设备, 虽然可以装虚拟机, 但也会多出许多平台特定Bug.
3. 带来的收益
花费这么大力气迁移到 Avalonia, 能增加多少潜在用户呢? 带来的收益能否抵消付出的时间呢?
4. UI风格
我还是挺喜欢微软的 Fluent Design, 不知道迁移到 Avalonia 是否依然能维持这种设计风格?

**Comment by textGamex** [comment]
如果可以的话,我们可以加QQ聊

**Comment by textGamex** [comment]
QQ: 2478444358

**Comment by PurplePlanen** [comment]
Of course, some people play Hearts of Iron 4 on Mac and Linux, but it's not the main one, so the author mainly develops the Windows version.

**Comment by PurplePlanen** [comment]
![image](https://github.com/user-attachments/assets/9b417a2f-8dc8-44db-a682-24c300910570)
😊
